### ISSUE TITLE
ClassNotFoundException when enabling plugin

### ISSUE THREAD

**Issue by KennethWussmann** [KennethWussmann/Levitate#11]
Issue by @toxicbyte
```
I have made a plugin with who I have added 3 commands hadler classes that use Levitate. 
However I get a ClassNotFoundException on de.ketrwu.levitate.Levitate.
```

```
Hey sorry I commented on the wrong project. 
Yes I used correct repository and dependencies with maven
```

**Comment by KennethWussmann** [comment]
@toxicbyte

Do you pack your Plugin with dependencies? Please open the JAR and check if these folders exist: `de -> ketrwu -> levitate`

If not, checkout my litte [Test-Plugin](https://github.com/KennethWussmann/Levitate-Test-Plugin) using Maven, Especially the [pom.xml build-section](https://github.com/KennethWussmann/Levitate-Test-Plugin/blob/master/pom.xml#L36-L59).

**Comment by toxicbyte** [comment]
I did just that. When I check under dependancies and open the levitate dependancy, there's definitebly the class. However I keep getting the error

**Comment by KennethWussmann** [comment]
Hm, I cannot reproduce your issue. Please attach your pom.xml.

**Comment by toxicbyte** [comment]
http://pastebin.com/9M5sKGBV

I added the maven-assembly plugin but now my file weights 25mb instead of 90kb. Is there another way arround?

**Comment by KennethWussmann** [comment]
Okay, you've a lot of dependencies :smiley: 

Just tell Maven to only pack Levitate and ignore the others:

```XML
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>1.6</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<minimizeJar>true</minimizeJar>
							<createDependencyReducedPom>false</createDependencyReducedPom>
							<artifactSet>
								<includes>
									<include>de.ketrwu:levitate</include>
								</includes>
							</artifactSet>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```

**Comment by toxicbyte** [comment]
Solved thanks
