### ISSUE TITLE
Syntax for optional arguments

### ISSUE THREAD

**Issue by TomiXo** [KennethWussmann/Levitate#34]
Hey! I know Levitate does not have optinal arguments but i really need them, there's a method to create them?

**Comment by KennethWussmann** [comment]
Hey TomiXo,
no this isn't possible and won't get implemented. 
This is against the philosophy of Levitate because you would have to decide what the user has entered.

You could do something like: 
```Java
@Command(syntax = "?kill", readable = "/kill", description = "Kill yourself")
public void killYourselfCommand(CommandSender sender, String cmd, ParameterSet args) {
    killCommand(sender, null, new ParameterSet(((Player) sender).getName());
}

@Command(syntax = "?kill <player[online]>", readable = "/kill <Player>", description = "Kill another player")
public void killCommand(CommandSender sender, String cmd, ParameterSet args) {
    args.getPlayer(0).setHealth(0);
}
```
So you would have `/kill` to kill yourself and `/kill Steve` to kill the online Player called `Steve`.

**Comment by TomiXo** [comment]
Thankks you

**Comment by TomiXo** [comment]
But, I can check if <player[online]> is null, and if it is, kill the player sender?

**Comment by KennethWussmann** [comment]
No, because
```
@Command(syntax = "?kill <player[online]>", readable = "/kill <Player>", description = "Kill another player")
public void killCommand(CommandSender sender, String cmd, ParameterSet args) {
    args.getPlayer(0).setHealth(0);
}
```
never get's called when `<player[online]>` is not passed by the user.
