### ISSUE TITLE
Annotation based registration

### ISSUE THREAD

**Issue by Chnkr** [KennethWussmann/Levitate#4]
I'd be a cool thing to have in large projects :+1:

**Comment by KennethWussmann** [comment]
Thanks for your request. I've added annotation-based command registration in [version 1.5.0](https://github.com/KennethWussmann/Levitate/releases/tag/v1.5.0)

**Comment by Chnkr** [comment]
Thanks a lot! I've been using https://github.com/crast/MondoCommand in the past, but it only allowed for registration of subcommands, switching to levitate now :+1:
